### ISSUE TITLE
Broadcasting two notifications with the same FriendlyName crashes with "KeyInUse"

### ISSUE THREAD

**Issue by BOLL7708** [artumino/SteamVR_HUDCenter#3]
Hello! I finally gave up on my own C# implementation of OpenVR notifications and used this, even if it's kind of old now it still works! Had to go down to 32-bit but that was no problem with the rest of the application, previously I used the 64-bit DLL for OpenVR.

In any case, I noticed that if I run the sample code (bottom of help) and submit Dummy twice I get a crash on RegisterNewItem(), see attached image. If I plug a UUID into the FriendlyName I avoid the crash, but this leaves me with an overlay/notification with a UUID in the displayed title. 

Is there any way around this? If not I think I'll just make a counter instead to reduce the amount of clutter in the title.

![image](https://cloud.githubusercontent.com/assets/12276837/24837815/7d9b94ec-1d3c-11e7-821d-7d9e1239ca33.png)

**Comment by artumino** [comment]
I'm pushing a fix for this now, you can now instantiate different overlays with the same name and register them both.

Having said that, If you only wanted to show multiple notifications you could have registered one Overlay and called DisplayNotification multiple times. 
You should also call RegisterNewItem only once per Overlay.

**Comment by BOLL7708** [comment]
Oops, I took the sample code and ran with it :P I've been registering every single notification, which now makes no sense. Thanks for clearing this up :)
